language: scala

dist: xenial

jdk: openjdk8

scala:
   - 2.9.3
   - 2.10.6
   - 2.11.11
   - 2.12.8

branches:
  only:
    - dev
    - dev_unstable
    - master

before_install:
    - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
    - bash -xv ./other_code/travis_ci/install_fpinscala.sh

script:
    - cd ./scala_initiatives/ && sbt compile && sbt test

# vim: set fileformat=unix filetype=yaml nowrap nospell :
